export const shlokas = [
  {
    chapter_id: "A",
    id: 1,
    shloka: "om pārthāya pratibodhitāṁ bhagavatā\n nārāyaṇena svayaṁ\n vyāsena grathitāṁ purāṇamuninā\n madhye mahābhāratam |\n advaitāmṛta-varṣiṇīṁ bhagavatīṁ\n aṣṭādaśādhyāyinīṁ\n ambatvām anusandadhāmi\n bhagavadgīte bhavadveṣiṇīm ||",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 2,
    shloka: "namo'stute vyāsa viśāla buddhe\n phullāravindāyata patranetra |\n yenatvayā bhārata taila pūrṇaḥ\n prajvālito jñāna mayaḥ pradīpaḥ ||",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 3,
    shloka: "prapanna pārijātāya\n totravetraika pāṇaye |\n jñānamudrāya kṛṣṇāya\n gītāmṛtaduhe namaḥ ||",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 4,
    shloka: "vasudeva sutaṁ devaṁ\n kaṁsa cāṇūra mardanam |\n devakī paramānandaṁ\n kṛṣṇaṁ vande jagadgurum ||",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 5,
    shloka: "bhīṣmadroṇataṭā jayadrathajalā\n gāndhāra nīlotpalā\n śalyagrāhavātī kṛpeṇa vahanī\n kārṇena velākulā |\n aśvatthāmā vikarṇa ghoramakarā\n duryodhanāvartinī\n sottīrṇā khalu pāṇḍavai raṇanadi\n kaivartakaḥ keśavaḥ ||",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 6,
    shloka: "pārāśarya vacassarojamamalaṁ\n gītārtha gandhotkaṭaṁ\n nānākhyānaka kesaraṁ harikathā\n sambodhanā bodhitam |\n loke sajana ṣaṭpadairaharahaḥ\n pepīyamānaṁ mudā\n bhūyāt bhārata paṅkajaṁ kalimala\n pradhvaṁsinaśśreyase ||\n",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 7,
    shloka: "mūkaṁ karoti vācālaṁ\n paṅguṁ laṅghayate girim |\n yat kṛpā tamahaṁ vande\n paramānanda mādhavam ||\n",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 8,
    shloka: "śāntākāraṁ bhujagaśayanam\n padmanābhaṁ sureśaṁ\n viśvādhāraṁ gaganasadṛśaṁ\n meghavarṇaṁ śubhāṅgam |\n lakśmīkāntaṁ kamalanayanam\n yogihṛddhyānagamyam\n vande viṣṇuṁ bhavabhayaharaṁ\n sarva lokaikanātham ||\n",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 9,
    shloka: "yaṁ brahmāvaruṇendrarudramarutaḥ\n stunvanti divyaisstavaiḥ\n vedaissāṅgapadakramopaniṣadaiḥ\n gāyanti yaṁ sāmagaḥ |\n dhyānāvasthita tadgatena manasā\n paśyanti yaṁ yoginaḥ\n yasyāntaṁ na vidussurāsuragaṇāḥ\n devāya tasmai namaḥ ||\n",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 10,
    shloka: "nārāyaṇaṁ namaskṛtya\n narañcaiva narottamam |\n devīṁ sarasvatīṁ vyāsaṁ\n tato jayamudīrayet ||\n",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 11,
    shloka: "saccidānandarūpāya\n kṛṣṇāyākliṣṭakāriṇe |\n namo vedāntavedyāya\n gurave buddhisākṣiṇe ||\n",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 12,
    shloka: "sarvopaniṣado gāvo\n dogdhā gopālanandanaḥ |\n pārtho vatsassudhīrbhoktā\n dugdhaṁ gītāmṛtaṁ mahat ||\n",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 13,
    shloka: "*gītāśāstramidaṁ puṇyam\n yaḥ paṭhet prayataḥ pumān |\n viṣṇoḥ padamavāpnoti\n bhaya-śokādi varjitaḥ ||\n",
    starred: false,
    note: "",
  },
  {
    chapter_id: "A",
    id: 14,
    shloka: "*ekaṁ śāstraṁ devakīputragītam\n eko devo devakīputra eva |\n eko mantrastasya nāmāni yāni\n karmāpyekaṁ tasya devasya sevā ||\n",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 1,
    shloka: "dhṛtarāṣṭra uvāca -\n dharmakṣetre kurukṣetre\n samavetā yuyutsavaḥ |\n māmakāḥ pāṇḍavāścaiva\n kimakurvata sañjaya ||",
    shloka_meaning: "Dhritarashtra asked:\n Sanjaya! On the sacred field of Kurukshetra, having gathered ready for battle, what have my son Duryodhana and the others, and the sons of Pandu, been doing?",
    noti_id: "1",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 2,
    shloka: "sañjaya uvāca -\n dṛṣṭvā tu pāṇḍavānīkaṁ\n vyūḍhaṁ duryodhanastadā |\n ācāryamupasaṅgamya\n rājā vacanamabravīt ||",
    shloka_meaning: "Sanjaya replied:\n Duryodhana, the prince, viewing the Pandava army arrayed for battle, approached his teacher Drona, and spoke thus:",
    noti_id: "2",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 3,
    shloka: "paśyaitāṁ pāṇḍuputrāṇām\n ācārya mahatīṁ camūm |\n vyūḍhāṁ drupadaputreṇa\n tava śiṣyeṇa dhīmatā ||",
    shloka_meaning: "O Master! See how your bright pupil Dhrishtadyumna, the son od King Drupada, has strategically arranged the army of the Pandavas!",
    noti_id: "3",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 4,
    shloka: "atra śūrā maheṣvāsāḥ\n bhīmārjunasamā yudhi |\n yuyudhāno virāṭaśca\n drupadaśca mahārathaḥ ||",
    noti_id: "4",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 5,
    shloka: "dhṛṣṭaketuścekitānaḥ\n kāśirājaśca vīryavān |\n purujitkuntibhojaśca\n śaibyaśca narapuṅgavaḥ ||",
    noti_id: "4",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 6,
    shloka: "yudhāmanyuśca vikrāntaḥ\n uttamaujāśca vīryavān |\n saubhadro draupadeyāśca\n sarva eva mahārathaḥ ||",
    shloka_meaning: "In this Pandava army, several great chariot warriors are gathered, every one of them equal in valor to Bhima and Arjuna, such as Yuyudhanu (Satyaki), Virata, Drupada, Dhrishtaketu, Chekitana, King of Kasi, Purujit, Kuntibhoja, and the noble Saibya, the valiant Yudhamanyu, powerful Uttamauja, Abhimanyu, the son of Subhadra, and the sons of Draupadi.",
    noti_id: "4",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 7,
    shloka: "asmākaṁ tu viśiṣṭā ye\n tānnibodha dvijottama |\n nāyakā mama sainyasya\n sañjñārthaṁ tānbravīmi te ||",
    shloka_meaning: "O noble brahmin, allow me to give you details of the warriors and commanders on our side.",
    noti_id: "5",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 8,
    shloka: "bhavān bhīṣmaśca karṇaśca\n kṛpaśca samitiñjayaḥ |\n aśvatthāmā vikarṇaśca\n saumadattistathaiva ca ||",
    shloka_meaning: "Yourself, Bhishma, Karna, the victorious Kripa, Aswatthama, Vikarna, the son of Somadatta (Bhoorisravas), and several others, are highly skillfull warriors on our side.",
    noti_id: "6",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 9,
    shloka: "anye ca bahavaśśūrāḥ\n madarthe tyaktajīvitāḥ |\n nānāśastrapraharaṇāḥ\n sarve yuddhaviśāradāḥ ||",
    shloka_meaning: "There are many other fighters, experts at missile warfare, now prepared to lay down their lives for me.",
    noti_id: "7",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 10,
    shloka: "aparyāptaṁ tadasmākaṁ\n balaṁ bhīṣmābhirakṣitam |\n paryāptaṁ tvidameteṣāṁ\n balaṁ bhīmābhirakṣitam ||",
    shloka_meaning: "The strength of our army, protected by Bhishma, is inadequate, wehras the strength of the Pandava army, protected by Bhima, is plentiful. (Although the Kaurava army was larger in numbers compared to that of the Pandava army, Duryodhana is expressing a contrary view, because, Bhishma's loyalty is undivided between both sides, whereas Bhima's loyalty is undivided. Hence, Duryodhana believes that the strength of the Pandavas is greater.)",
    noti_id: "8",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 11,
    shloka: "ayaneṣu ca sarveṣu\n yathābhāgamavasthitāḥ |\n bhīṣmamevābhirakṣantu\n bhavantassarva eva hi ||",
    shloka_meaning: "Therefore, each of you, holding your commanding posts, must focus on safeguarding Bhishma at any cost. It is Bhishma who will protect the rest of us.",
    noti_id: "9",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 12,
    shloka: "tasya sañjanayanharṣaṁ\n kuruvṛddhaḥ pitāmahaḥ |\n siṁhanādaṁ vinadyoccaiḥ\n śaṅkhaṁ dadhmau pratāpavān ||",
    shloka_meaning: "Hearing the deferential words spoken by Duryodhana, the hoary and venerable Bhishma, roaring like a lion, blew his conch. Duryodhana's heart swelled with joy.",
    noti_id: "10",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 13,
    shloka: "tataśśaṅkhāśca bheryaśca\n paṇavānakagomukhāḥ |\n sahasaivābhyahanyanta\n saśabdastumulo'bhavat ||",
    shloka_meaning: "Bhishma's zeal for battle raised the spirits of all the assembled warriors. A massive clamor arose all at once, with the blowing of conches, sounding of trumpets, and beating of war drums.",
    noti_id: "11",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 14,
    shloka: "tataśśvetairhayairyukte\n mahati syandane sthitau |\n mādhavaḥ pāṇḍavaścaiva\n divyau śaṅkhau pradadhmatuḥ ||",
    shloka_meaning: "Concurrently, Sri Krishna and Arjuna, seated in a divine chariot tethered with white horses also blew their conches, signaling readiness for battle.",
    noti_id: "12",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 15,
    shloka: "pāñcajanyaṁ hṛṣīkeśaḥ\n devadattaṁ dhanañjayaḥ |\n pauṇḍraṁ dadhmau mahāśaṅkhaṁ\n bhīmakarmā vṛkodaraḥ ||",
    shloka_meaning: "Hrishikesa (Krishna) blew the conch Panchajanya. Dhananjaya (Arjuna) blew the conch Devadatta. Striking terror, Bhima blew the Paundra.",
    noti_id: "13",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 16,
    shloka: "anantavijayaṁ rājā\n kuntīputro yudhiṣṭhiraḥ |\n nakulassahadevaśca\n sughoṣamaṇipuṣpakau ||",
    shloka_meaning: "Kunti's son Yudhishthira (Dharmaraja) blew Ananta Vijaya. Nakula blew the Sugosha. Sahadeva blew the conch Manipushpaka.",
    noti_id: "14",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 17,
    shloka: "kāśyaśca parameṣvāsaḥ\n śikhaṇḍī ca mahārathaḥ |\n dhṛṣṭadyumno virāṭaśca\n sātyakiścāparājitaḥ ||",
    noti_id: "15",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 18,
    shloka: "drupado draupadeyāśca\n sarvaśaḥ pṛthivīpate |\n soubhadraśca mahābāhuḥ\n śaṅkhāndadhmuḥ pṛthakpṛthak ||",
    shloka_meaning: "The King of Kasi, the great bowman, the great chariot warrior Sikhandi, Dhrishtadyumna, Virata, the undefeatable Satyaki, Drupada, the sons of Draupadi, and the strong son of Subhadra also blew their respective conches, one after another from all directions.",
    noti_id: "15",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 19,
    shloka: "sa ghoṣo dhārtarāṣṭrāṇāṁ\n hṛdayāni vyadārayat |\n nabhaśca pṛthivīṁ caiva\n tumulo vyanunādayan ||",
    shloka_meaning: "The earth and the sky reverberated with the defeaning tumult. The dreadful din drained courage from the hearts of the sons of Dhritarashtra.",
    noti_id: "16",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 20,
    shloka: "atha vyavasthitāndṛṣṭvā\n dhārtarāṣṭrānkapidhvajaḥ |\n pravṛtte śastrasampāte\n dhanurudyamya pāṇḍavaḥ ||",
    noti_id: "17",
    starred: false,
    note: "",
  },
  {
    chapter_id: "1",
    id: 21,
    shloka: "hṛṣīkeśaṁ tadā vākyam\nidam āha mahīpate |\n[[MEANING_HERE]]\narjuna uvāca —\nsenayor ubhayor madhye\nrathaṁ sthāpaya me 'cyuta ||",
    shloka_meaning: "O King! Arjuna, whose flag bears the emblem of Hanuman, strung his bow. Looking at the sons of Dhritarashtra rearing their heads for battle, he said to Sri Krishna:",
    noti_id: "18",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1", 
    id: 22,
    shloka: "yāvadetānnirīkṣe'haṁ\n yoddhukāmānavasthitān |\n kairmayā saha yoddhavyam\n asmin raṇasamudyame ||",
    noti_id: "19",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 23,
    shloka: "yotsyamānānavekṣe'haṁ\n ya ete'tra samāgatāḥ |\n dhārtarāṣṭrasyadurbuddheḥ\n yuddhe priyacikīrṣavaḥ ||",
    shloka_meaning: "I am looking at all these warriors who have come here to fight. In this great battle, I know who is destined to fight against whom. I wish to see once all the valiant heroes who ahve assembled here to help the evil-minded Duryodhana. Sri Krishna, park my chariot in the middle of the two armies.",
    noti_id: "19",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 24,
    shloka: "sañjaya uvāca —\n evamukto hṛṣīkeśaḥ\n guḍākeśena bhārata |\n senayorubhayormadhye\n sthāpayitvā rathottamam ||",
    noti_id: "20",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 25,
    shloka: "bhīṣmadroṇapramukhataḥ\n sarveṣāṁ ca mahīkṣitām |\n uvāca pārtha paśyaitān\n samavetānkurūniti ||",
    shloka_meaning: "Sanjaya said: Dhritarashtra! When Arjuna, the conqueror of sleep, spoke thus to Sri Krishna, Sri Krishna stopped his chariot between the two armies, facing the great Bhishma and Drona, and said,'Arjuna, look at the Kaurava warriors thirsting for battle.",
    noti_id: "20",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 26,
    shloka: "tatrāpaśyatsthitānpārthaḥ\n pitṝnatha pitāmahān |\n ācāryānmātulānbhrātṛn\n putrānpautrānsakhīṁstathā || śvaśurānsuhṛdaścaiva\n senayorubhayorapi |",
    shloka_meaning: "Arjuna saw, assembled in both the armies, many respectable fatherly figures (like Bhoorisravas), grandfathers (like Bhishma), preceptors (like Drona), maternal uncles (like Salya), brothers, cousins (like Duryodhana), sons (like Lakshmana), friends (like Aswatthama), close pals (like Kritavarma), and grandchildren.",
    noti_id: "21",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "1",
    id: 27,
    shloka: "tānsamīkṣya sa kaunteyaḥ\n sarvānbandhūnavasthitān |\n kṛpayā parayā''viṣṭaḥ\n viṣīdannidamabravīt ||",
    shloka_meaning: "Seeing all the gathered relatives, heart-broken with sadness and pity,",
    noti_id: "22",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 28,
    shloka: "arjuna uvāca —\n dṛṣṭvemaṁ svajanaṁ kṛṣṇa\n yuyutsuṁ samupasthitam |\n sidanti mama gātrāṇi\n mukhaṁ ca pariśuṣyati ||",
    noti_id: "23",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 29,
    shloka: "vepathuśca śarīre me\n romaharṣaśca jāyate |\n gāṇḍīvam sraṁsate hastāt | tvakcaiva paridahyate ||",
    shloka_meaning: "Arjuna said: Sri Krishna! I am losing control over my body seeing my near and dear relatives assembled here for war. My mouth dries up. My frame trembles. The Gandiva (bow) slips from my hand. My skin burns. My hair stands on end.",
    noti_id: "23",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 30,
    shloka: "na ca śaknomyavasthātuṁ\n brahmatīva ca me manah |\n nimittāni ca paśyāmi\n viparītāni keśava ||",
    shloka_meaning: "My knees are buckling under me. My mind is frenzied. I see bad omens.",
    noti_id: "24",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 31,
    shloka: "na ca śreyo'nupaśyāmi\n hatvā svajanamāhave |\n na kāṅkṣe vijayaṁ kṛṣṇa\n na ca rājyaṁ sukhāni ca ||",
    shloka_meaning: "Sri Krishna! I see absolutely no merit in killing so many relatives. I have no desire for victory in war, for the luxuries of a kingdom, or for any enjoyments.",
    noti_id: "25",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 32,
    shloka: "kiṁ no rājyena govinda\n kiṁ bhogairjīvitena vā ||",
    noti_id: "26",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 33,
    shloka: "yeṣāmarthe kāṅkṣitaṁ naḥ\n rājyaṁ bhogāssukhāni ca |\n ta ime'vasthitā yuddhe\n prāṇāṁstyaktvā dhanāni ca ||",
    noti_id: "26",
    starred: 0,
  },
  {
    chapter_id: "1",
    id: 34,
    shloka: "ācāryāḥ pitaraḥ putrāḥ\n tathaiva ca pitāmahāḥ |\n mātulāśśvaśurāḥ pautrāḥ\n śyālāssambandhinastathā",
    shloka_meaning: "O Govinda! Of what use is the gaining of a kingdom and its royal comforts, if it is only to lead a life without purpose? Those, for whose sake we wish to have the comforts of a kingdom, those same people, the gurus, fathers, sons, grandfathers, uncles, grandsons, brothers-in-law, and the other relatives, are now gathered here on this battleground, relinquising wealth, and even their very desire to live.",
    noti_id: "26",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 35,
    shloka: "etānna hantumicchāmi\n ghnato'pi madhusūdana |\n api trailokyarājyasya\n hetoḥ kiṁ nu mahīkṛte ||",
    shloka_meaning: "I have no desire to kill them, Sri Krishna, even if they were to kill me. Not just for this kingdom, but for lordship of all three worlds, I would still not kill them.",
    noti_id: "27",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 36,
    shloka: "nihatya dhārtarāṣṭrānnaḥ\n ka prītissyājjanārdana |\n pāpam evāśrayedasmān\n hatvaitānātatāyinaḥ ||",
    shloka_meaning: "What happiness would I derive by killing Duryodhana and the other relatives, Sri Krishna? Although they are rogues, we would only incur sin by killing them. (Rogues are defined as those who would set fire to homes, administer poison, take up weapons to kill, steal wealth, missapropriate land, and abduct wives. As per Dharma Sastra, killing such scoundrels is not wrong. Yet Arjuna believes otherwise.)",
    noti_id: "28",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 37,
    shloka: "tasmānnārha vayaṁ hantuṁ\n dhārtarāṣṭrānsvabāndhavān |\n svajanaṁ hi kathaṁ hatvā\n sukhinassyāma mādhava ||",
    shloka_meaning: "Hence, it is not proper for me to kill Duryodhana and the other relatives. By killing them, how can we possibly find happiness?",
    noti_id: "29",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1", 
    id: 38,
    shloka: "yadyapyete na paśyanti\n lobhopahatacetasaḥ\n kulakṣayakṛtaṁ doṣaṁ\n mitradrohe ca pātakam ||",
    noti_id: "30",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 39,
    shloka: "kathaṁ na jñeyamasmābhiḥ\n pāpādasmānnivartitum\n kulakṣayakṛtaṁ doṣaṁ\n prapaśyadbhirjanārdana ||",
    shloka_meaning: "They have lost their discretion due to greed for the kingdom. They fail to recognize the sin of destroying family lineage and betraying friendship. I know the evil inherent in the destruction of the family lineage.",
    noti_id: "30",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 40,
    shloka: "kulakṣaye praṇaśyanti\n kuladharmāssanātanāḥ |\n dharme naṣṭe kulaṁ kṛtsnam\n adharmo'bhibhavatyuta ||",
    shloka_meaning: "When family is destroyed, ancient traditions are wiped out. When Dharma is ruined, customs crumble. Adharma becomes rampant.",
    noti_id: "31",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 41,
    shloka: "adharmābhibhavātkṛṣṇa\n praduṣyanti kulastriyaḥ |\n strīṣu duṣṭāsu vārṣṇeya\n jāyate varṇasaṅkaraḥ ||",
    shloka_meaning: "Sri Krishna! When Adharma spreads, women lose their chastity. When women become unchaste, aristocracy is lost.",
    noti_id: "32",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 42,
    shloka: "saṅkaro narakāyaiva\n kulaghnānāṁ kulasya ca |\n patanti pitaro hyeṣāṁ\n luptapiṇḍodakakriyāḥ ||",
    shloka_meaning: "When good breeding is lost, those responsible for it will go to hell. The forefathers, deprived of offerings by their progeny, will fall into degradation.",
    noti_id: "33",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 43,
    shloka: "doṣairetaiḥ kulaghnānāṁ\n varṇasaṅkarakārakaiḥ |\n utsādyante jātidharmāḥ\n kuladharmāśca śāśvatāḥ ||",
    shloka_meaning: "Adulteration of family lineage roots out all hoary traditions, customs, and mores of society.",
    noti_id: "34",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 44,
    shloka: "utsannakuladharmāṇāṁ\n manuṣyāṇāṁ janārdana |\n narake'niyatam vāsaḥ\n bhavatītyanuśuśruma ||",
    shloka_meaning: "We hear that those who break family traditions will certainly live in hell.",
    noti_id: "35",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 45,
    shloka: "aho bata mahatpāpaṁ\n kartuṁ vyavasitā vayam |\n yadrājyasukhalobhena\n hantuṁ svajanamudyatāḥ",
    shloka_meaning: "Sri Krishna! We are on the brink of committing a horrendous sin. We will accumulate only sin, if we proceed to kill these relatives out of greed for the luxuries of a kingdom.",
    noti_id: "36",
    starred: 0,
    note: ""
  },
  {
    chapter_id: "1",
    id: 46,
    shloka: "yadi māmapratīkāram\n aśastram śastrapāṇayaḥ |\n dhārtarāṣṭrā raṇe hanyuḥ\n tanme kṣemataraṁ bhavet ||",
    shloka_meaning: "If Duryodhana and the others kill me, while I am unarmed and choose not to defend myself, I would prefer such a death, to this fate.",
    noti_id: "37",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "1",
    id: 47,
    shloka: "sañjaya uvāca -\n evamuktvā'rjunassaṅkhye\n rathopastha upāviśat |\n visṛjya saśaraṁ cāpaṁ\n śokasaṁvignamānasaḥ ||",
    shloka_meaning: "Sanjaya said: Arjuna, speaking thus, with a mind englufed in sorrow, dropped his bow and arrows, and slumped in the chariot.",
    noti_id: "38",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 29,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 31,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 32,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 33,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 34,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 35,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 36,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 37,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 38,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 39,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 40,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 41,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "2",
    id: 42,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 29,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 31,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 32,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 33,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 34,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 35,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 36,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 37,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 38,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 39,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 40,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 41,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 42,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "3",
    id: 43,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 29,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 31,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 32,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 33,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 34,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 35,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 36,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 37,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 38,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 39,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 40,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 41,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "4",
    id: 42,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 31,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 32,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 33,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 34,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 35,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 36,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 37,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 38,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 39,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 40,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 41,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 42,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 43,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 44,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 45,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 46,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "6",
    id: 47,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 29,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "7",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "8",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 29,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 31,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 32,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 33,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "9",
    id: 34,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 29,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 31,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 32,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 33,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 34,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 35,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 36,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 37,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 38,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 39,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 40,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 41,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "10",
    id: 42,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 29,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 31,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 32,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 33,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 34,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 35,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 36,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 37,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 38,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 39,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 40,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 41,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 42,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 43,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 44,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 45,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 46,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 47,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 48,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 49,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 50,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 51,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 52,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 53,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 54,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "11",
    id: 55,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "12",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 29,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 31,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 32,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 33,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 34,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "13",
    id: 35,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "14",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "15",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "16",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "17",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 1,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 2,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 3,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 4,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 5,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 6,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 7,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 8,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 9,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 10,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 11,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 12,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 13,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 14,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 15,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 16,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 17,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 18,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 19,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 20,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 21,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 22,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 23,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 24,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 25,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 26,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 27,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 28,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 29,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 30,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 31,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 32,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 33,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 34,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 35,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 36,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 37,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 38,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 39,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 40,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 41,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 42,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 43,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 44,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 45,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 46,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 47,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 48,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 49,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 50,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 51,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 52,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 53,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 54,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 55,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 56,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 57,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 58,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 59,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 60,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 61,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 62,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 63,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 64,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 65,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 66,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 67,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 68,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 69,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 70,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 71,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 72,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 73,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 74,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 75,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 76,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 77,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
  {
    chapter_id: "18",
    id: 78,
    shloka: "",
    shloka_meaning: "",
    noti_id: "",
    starred: 0,
    note: "",
  },
];